version: '2.1'

services:
  backend:
    build:
      context: ./Backend/
    volumes:
      - ./Backend/:/usr/app
      - /usr/app/node_modules
    env_file:
      - ./.env
    environment:
      BASE_URL: "http://localhost:3333"
      MONGODB_CONNECTION_STRING: "${MONGODB_CONNECTION_STRING}"
    ports:
      - 3333:3333
  web:
    build:
      context: ./Web/
    volumes:
      - ./Web/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    ports:
      - 3000:3000
  # mobile:
  #   build:
  #     context: ./mobile/
  #   volumes:
  #     - ./mobile/:/usr/app
  #     - /usr/app/node_modules
  #   depends_on:
  #     - backend
  #   ports:
  #     - 19000:19000
  #     - 19001:19001
  #     - 19002:19002